sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
